baseURL = "https://jcmorin.dev/"
languageCode = "en-us"
title = "jcmorin.dev"

enableEmoji = true

defaultContentLanguage = "en"

[languages.en]
weight = 0
languageName = "English"

[[languages.en.menu.main]]
name   = "home"
url = "/"
weight = 1
title = "Home"

[[languages.en.menu.main]]
name   = "about"
url = "/about/"
weight = 2
title = "About"

[languages.fr]
weight = 10
languageName = "Français"

[[languages.fr.menu.main]]
name   = "home"
url = "/"
weight = 1
title = "Accueil"

[[languages.fr.menu.main]]
name   = "about"
url = "/about/"
weight = 2
title = "À propos"

[markup]
  [markup.highlight]
    style = "dracula"

[params]
  images = ["img/shorts.svg"]

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js"
    target = "static/js/bootstrap"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
