name: build

on:
  push:
    branches:
      - '*'  # Set a branch to deploy
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        cd /opt
        wget https://github.com/sass/dart-sass-embedded/releases/download/1.0.0-beta.7/sass_embedded-1.0.0-beta.7-linux-x64.tar.gz && \
        tar xvfz sass_embedded-1.0.0-beta.7-linux-x64.tar.gz && \
        rm sass_embedded-1.0.0-beta.7-linux-x64.tar.gz
      name: Install Dart Sass

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.84.1'
        extended: true

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: yarn install --frozen-lockfile

    - name: Build
      run: |
        export PATH=/opt/sass_embedded:$PATH
        hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
